/*
SQLyog Ultimate v12.5.1 (64 bit)
MySQL - 8.0.30 : Database - contoh
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`contoh` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `contoh`;

/*Table structure for table `cake` */

DROP TABLE IF EXISTS `cake`;

CREATE TABLE `cake` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name_cake` varchar(75) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `price` double DEFAULT '0',
  `description` text COLLATE utf8mb4_general_ci,
  `url_image` varchar(250) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `type` enum('birthday','wedding','custom') COLLATE utf8mb4_general_ci DEFAULT NULL,
  `status` tinyint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  KEY `type` (`type`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Data for the table `cake` */

insert  into `cake`(`id`,`name_cake`,`price`,`description`,`url_image`,`type`,`status`) values 
(1,'Birthday Cake 01',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-1.jpg','birthday',1),
(2,'Birthday Cake 02',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-1.jpg','birthday',1),
(3,'Birthday Cake 03',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-1.jpg','birthday',1),
(4,'Birthday Cake 04',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-1.jpg','birthday',1),
(5,'Birthday Cake 05',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-1.jpg','birthday',1),
(6,'Birthday Cake 06',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-1.jpg','birthday',1),
(7,'Wedding Cake 01',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-2.jpg','wedding',1),
(8,'Wedding Cake 02',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-2.jpg','wedding',1),
(9,'Wedding Cake 03',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-2.jpg','wedding',1),
(10,'Wedding Cake 04',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-2.jpg','wedding',1),
(11,'Wedding Cake 05',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-2.jpg','wedding',1),
(12,'Wedding Cake 06',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-2.jpg','wedding',1),
(13,'Custom Cake 01',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-3.jpg','custom',1),
(14,'Custom Cake 02',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-3.jpg','custom',1),
(15,'Custom Cake 03',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-3.jpg','custom',1),
(16,'Custom Cake 04',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-3.jpg','custom',1),
(17,'Custom Cake 05',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-3.jpg','custom',1),
(18,'Custom Cake 06',99,'Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo\r\nIpsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo Ipsum ipsum clita erat amet dolor sit justo sea eirmod diam stet sit justo','assets/img/cake-3.jpg','custom',1);

/*Table structure for table `chef` */

DROP TABLE IF EXISTS `chef`;

CREATE TABLE `chef` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `full_name` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `jobs` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `url_image` varchar(250) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `status` tinyint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Data for the table `chef` */

insert  into `chef`(`id`,`full_name`,`jobs`,`url_image`,`status`) values 
(1,'Chef 01','Designation','assets/img/team-1.jpg',1),
(2,'Chef 02','Designation','assets/img/team-2.jpg',1),
(3,'Chef 03','Designation','assets/img/team-3.jpg',1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
